spring:
  datasource:
    platform: h2
    sql-script-encoding: utf-8
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: true
  data:
    rest:
      enable-enum-translation: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public

logging:
  level:
    root: 'INFO'
    org.hibernate.SQL: DEBUG

server:
  port: 10000